######################################################################
# Automatically generated by qmake (2.01a) lun. 20. avr. 15:07:38 2009
######################################################################
QT += widgets
TEMPLATE = app
TARGET = generateur
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwin.h sheet.h
SOURCES += main.cpp mainwin.cpp sheet.cpp
